function [ output_args ] = DivideCluster( img )
% divide and conquer
    [height, width, channelCnt] = size(img);
    imgList = reshape(img, height*width, channelCnt);
    imgList = double(imgList);
    mainColors = [255, 255, 255; ...
        255, 0, 0; ...
        0, 255, 0; ...
    	0, 0, 255; ...
    	255, 255, 0; ...
    	0, 255, 255; ...
    	255, 0, 255; ...
    	0, 0, 0];
    colorVectList = zeros([height*width, size(mainColors, 1)]);
    for i = 1 : size(colorVectList, 1)
        colorVectList(i, :) = ColorVector(imgList(i,:), mainColors);
    end
    [idx, centers] = kmeans(colorVectList, 3);
    imgMask = reshape(idx, height, width);
    figure; imagesc(imgMask);
    disp(centers);
end

