function CreateColorContourFigure(colorContour, fig, handle)
%CREATEFIGURE(ZDATA1, CDATA1)
%  ZDATA1:  contour z
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 19-Mar-2016 23:21:34

% Create axes
axes1 = handle;
hold(axes1,'on');

% Create contour
contour(colorContour);

% Create image
image(fig,'Parent',axes1,'CDataMapping','scaled','AlphaData',0.1);

box(axes1,'on');
axis(axes1,'tight');
% Set the remaining axes properties
set(axes1,'BoxStyle','full','Layer','top', 'ydir','reverse');
