function CreateClusterFigure(clusterResult, handle)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 22-Mar-2016 22:44:27

% Create axes
axes1 = handle;
hold(axes1,'on');

% Create image
image(clusterResult,'Parent',axes1,'CDataMapping','scaled');

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 481.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 321.5]);
box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'Layer','top');
